apiVersion: v1
kind: Secret
metadata:
  name: pythonwiki-db-secret
  namespace: pythonwiki
type: Opaque
stringData:
  MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
  CONNECTION_STRING: "Server=pythonwiki-db,1433;Database=PythonWikiDb;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;MultipleActiveResultSets=true;Pooling=true;Min Pool Size=5;Max Pool Size=100"
