apiVersion: v1
kind: Service
metadata:
  name: pythonwiki-db
  namespace: pythonwiki
spec:
  type: ClusterIP
  selector:
    app: pythonwiki-db
  ports:
    - name: sqlserver
      port: 1433
      targetPort: 1433
